### ISSUE TITLE
Tuesday, July 26th 2016 - Scratch Pad + Summary 

### ISSUE THREAD

**Issue by jendiamond** [LAXercism/mobprogramminglax#1]

**Comment by MrExeter** [comment]
Psql cheatsheet : 
http://www.postgresonline.com/downloads/special_feature/postgresql83_psql_cheatsheet.pdf

**Comment by MrExeter** [comment]
bundle exec rake test TEST=test/acceptance/team_test.rb

**Comment by jendiamond** [comment]
foreman s -p 4567

puts page.html
