### ISSUE TITLE
 Tuesday, August 9th 2016 - Scratch Pad + Summary 

### ISSUE THREAD

**Issue by MrExeter** [LAXercism/mobprogramminglax#3]
We think we need to create 51 UserExercises for the page to paginate.
Is it possible to pass a parameter to change the default number of things per page?

Can one User submit 51 UserExercises, each with 1 submission
OR 51 Users submit the same submission of the same UserExercise?
Is one of these better than the other?
Which one creates fewer database records?

We also noticed another bug within this bug.
Interesting find! Do you see why it works there and not in the other cases?

**Comment by jendiamond** [comment]
We ran the tests with pry

```
    with_login(user) do
      visit("/teams/some-team/streams?per_page=2")
      require 'pry'; binding.pry
      click_link("2")
    end
```

and then ran this in the pry repl:

`target = open('page.html', 'w')`

`target.write(page.html)`

`target.close`

BE SURE TO EXIT PRY!

# 

cd /tmp  
cp page.html /vagrant

---

### When we ran the page in Chrome the error we received is:

#### We assume means that we are not creating the activity properly

```
NoMethodError at /teams/some-team/streams undefined method `to_datetime' for nil:NilClass  
file: stream_exercise.rb location: at line: 10
```

### Check this out next time:

`test/apps/submission_test.rb`  
   sub = Submission.create(data.merge(created_at: Time.now - 10))

---

To change the default editor that your terminal opens in:  
`sudo update-alternatives --config editor`

**Comment by jendiamond** [comment]
### This works but it doesn't paginate

``` ruby
def test_team_pagination

  user = User.create(username: "foobar", github_id: 123)
  attributes = { slug: 'some-team', name: 'Some Team', confirmed: true }
  team = Team.by(user).defined_with(attributes, user)
  team.save!

  TeamMembership.create!(team_id: team.id, user_id: user.id, confirmed: true)

  WillPaginate.per_page = 2

  submission = Submission.create(user: user,
                               language: 'ruby',
                               slug: 'leap',
                               solution: { 'leap.rb': 'CODE' },
                               created_at: Time.now - 10)
  3.times do |index|
    UserExercise.create(user: user,
                      submissions: [submission],
                      language: 'fake',
                      slug: "apple#{index}",
                      iteration_count: 1)
  end

  with_login(user) do
    visit("/teams/some-team/streams")
    click_link("2")
  end
end

#pagination_menu_item.total
# from: Post.paginate(:page => params[:page], :per_page => 30)
# Post.paginate(:page => params[:page], :per_page => 30)
```

![ex](https://cloud.githubusercontent.com/assets/751697/17562793/463d77aa-5ee1-11e6-8ca7-9c9faf48e9c6.png)
![ex2](https://cloud.githubusercontent.com/assets/751697/17562794/48ad6ef0-5ee1-11e6-9228-72bf87ced767.png)

**Comment by jendiamond** [comment]
kytrinyx says...
If you want to have two pages you'll probably need to pass ?per_page=2 here.
