### ISSUE TITLE
Wednesday, October 28th 2016 

### ISSUE THREAD

**Issue by jendiamond** [LAXercism/mobprogramminglax#8]
#### At the Fullstack Meetup at Pivotal 
@jendiamond @Taekyoon @machikoyasuda  

Working on this section of the code:
**`lib/exercism/team_stream.rb`**  
```
@@ -8,11 +8,12 @@
 class TeamStream
   attr_reader :team, :viewer_id, :page, :track_id, :user_id, :username, :slug
   attr_accessor :per_page

  def initialize(team, viewer_id, page=1, per_page=50)
...
```
@kytrinyx  commented:  
This is not going to get the default when you pass params['per_page'] with nil. I would suggest adding the || 50 to the call in the route file.

---

We changed this in **`app/routes/teams.rb`**
```ruby
locals = {
            team: team,
            stream: TeamStream.new(team, current_user.id, params['page'] || 1, params['per_page'] || 50),
            active: 'stream',
          }
```

**Comment by machikoyasuda** [comment]
@jendiamond what is the meetup URL rsvp for ur meetup
